#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineStorePlatform
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="onlineStoreDB")]
	public partial class OnlineStoreDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDB_User(DB_User instance);
    partial void UpdateDB_User(DB_User instance);
    partial void DeleteDB_User(DB_User instance);
    #endregion
		
		public OnlineStoreDBDataContext() : 
				base(global::OnlineStorePlatform.Properties.Settings.Default.onlineStoreDBConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineStoreDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineStoreDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineStoreDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineStoreDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DB_User> DB_Users
		{
			get
			{
				return this.GetTable<DB_User>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DB_User")]
	public partial class DB_User : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _BD_Id;
		
		private string _DB_Fullname;
		
		private string _DB_Username;
		
		private string _DB_Email;
		
		private string _DB_Password;
		
		private int _DB_Type;
		
		private int _DB_Age;
		
		private string _DB_Gender;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBD_IdChanging(int value);
    partial void OnBD_IdChanged();
    partial void OnDB_FullnameChanging(string value);
    partial void OnDB_FullnameChanged();
    partial void OnDB_UsernameChanging(string value);
    partial void OnDB_UsernameChanged();
    partial void OnDB_EmailChanging(string value);
    partial void OnDB_EmailChanged();
    partial void OnDB_PasswordChanging(string value);
    partial void OnDB_PasswordChanged();
    partial void OnDB_TypeChanging(int value);
    partial void OnDB_TypeChanged();
    partial void OnDB_AgeChanging(int value);
    partial void OnDB_AgeChanged();
    partial void OnDB_GenderChanging(string value);
    partial void OnDB_GenderChanged();
    #endregion
		
		public DB_User()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BD_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int BD_Id
		{
			get
			{
				return this._BD_Id;
			}
			set
			{
				if ((this._BD_Id != value))
				{
					this.OnBD_IdChanging(value);
					this.SendPropertyChanging();
					this._BD_Id = value;
					this.SendPropertyChanged("BD_Id");
					this.OnBD_IdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Fullname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DB_Fullname
		{
			get
			{
				return this._DB_Fullname;
			}
			set
			{
				if ((this._DB_Fullname != value))
				{
					this.OnDB_FullnameChanging(value);
					this.SendPropertyChanging();
					this._DB_Fullname = value;
					this.SendPropertyChanged("DB_Fullname");
					this.OnDB_FullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DB_Username
		{
			get
			{
				return this._DB_Username;
			}
			set
			{
				if ((this._DB_Username != value))
				{
					this.OnDB_UsernameChanging(value);
					this.SendPropertyChanging();
					this._DB_Username = value;
					this.SendPropertyChanged("DB_Username");
					this.OnDB_UsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DB_Email
		{
			get
			{
				return this._DB_Email;
			}
			set
			{
				if ((this._DB_Email != value))
				{
					this.OnDB_EmailChanging(value);
					this.SendPropertyChanging();
					this._DB_Email = value;
					this.SendPropertyChanged("DB_Email");
					this.OnDB_EmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DB_Password
		{
			get
			{
				return this._DB_Password;
			}
			set
			{
				if ((this._DB_Password != value))
				{
					this.OnDB_PasswordChanging(value);
					this.SendPropertyChanging();
					this._DB_Password = value;
					this.SendPropertyChanged("DB_Password");
					this.OnDB_PasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Type", DbType="Int NOT NULL")]
		public int DB_Type
		{
			get
			{
				return this._DB_Type;
			}
			set
			{
				if ((this._DB_Type != value))
				{
					this.OnDB_TypeChanging(value);
					this.SendPropertyChanging();
					this._DB_Type = value;
					this.SendPropertyChanged("DB_Type");
					this.OnDB_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Age", DbType="Int NOT NULL")]
		public int DB_Age
		{
			get
			{
				return this._DB_Age;
			}
			set
			{
				if ((this._DB_Age != value))
				{
					this.OnDB_AgeChanging(value);
					this.SendPropertyChanging();
					this._DB_Age = value;
					this.SendPropertyChanged("DB_Age");
					this.OnDB_AgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DB_Gender", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DB_Gender
		{
			get
			{
				return this._DB_Gender;
			}
			set
			{
				if ((this._DB_Gender != value))
				{
					this.OnDB_GenderChanging(value);
					this.SendPropertyChanging();
					this._DB_Gender = value;
					this.SendPropertyChanged("DB_Gender");
					this.OnDB_GenderChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
