<?xml version="1.0" encoding="utf-8"?><Database Name="onlineStoreDB" Class="OnlineStoreDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=onlineStoreDB;Integrated Security=True" SettingsObjectName="OnlineStorePlatform.Properties.Settings" SettingsPropertyName="onlineStoreDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DB_User" Member="DB_Users">
    <Type Name="DB_User">
      <Column Name="BD_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DB_Fullname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DB_Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DB_Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DB_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DB_Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DB_Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DB_Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>